- 素敵ですね！
- いい写真！
- 羨ましいです
- 楽しそう！
- 行ってみたい！
- 美味しそう！
- 綺麗ですね
- 最高！
- お疲れ様です
- また見に来ます！
- すごい！
- いいね〜
- 最高の一日ですね
- 素敵な場所
- また行きたい
- 憧れます
- 癒されました
- おしゃれ
- かっこいい
- 参考になります
- Nice!
- Beautiful!
- Looks great!
- Amazing!
- Cool!
- Love it!
- So good!
- Wonderful!
- Awesome!
- Great shot!
